name: mtc2018_app
description: The Official Conference App for Mercari Tech Conf 2018

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  json_annotation: ^0.2.3
  url_launcher: ^3.0.3
  font_awesome_flutter: ^8.0.1
  firebase_messaging: ^2.0.0
  share: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.6.0"
  build_runner: ^0.9.0
  json_serializable: ^0.5.4
  mockito: ^3.0.0
  
flutter_icons:
  android: true
  ios: true
  image_path_ios: "images/ios_icn.png"
  image_path_android: "images/android_icn.png"

flutter:
  uses-material-design: true
  assets:
   - images/about_icn.png
   - images/about_icn_active.png
   - images/about_logo.png
   - images/navbar_icn.png
   - images/booth_a.png
   - images/booth_b.png
   - images/booth_a_01.png
   - images/booth_a_02.png
   - images/booth_a_03.png
   - images/booth_a_04.png
   - images/booth_a_05.png
   - images/booth_a_06.png
   - images/booth_a_07.png
   - images/booth_a_08.png
   - images/booth_a_09.png
   - images/booth_b_10.png
   - images/booth_b_11.png
   - images/booth_b_12.png
   - images/exhibition2.jpg
   - images/exhibition7.png
   - images/tab_all.png
   - data/exhibitions.json